/**
 * GENERATED FILE — do not edit by hand.
 *
 * Written by `npm run sprites:emotions -- --promote`. Lists the emotion clips that actually
 * exist on disk under `public/assets/characters/emotions/`; regenerate rather than editing,
 * or the next promote will overwrite your change.
 *
 * A committed generated module rather than a JSON file fetched at runtime, for two reasons:
 * Phaser's loader would need a second pass (read the index, then queue the sheets it names),
 * and a TS module gets the animal ids and emotion names type-checked against
 * `AnimalSpriteId` / `AnimalEmotion` at build time instead of failing silently at runtime.
 *
 * Empty is a valid state: every consumer falls back to the base `idle`/`alert` behaviour for
 * an animal or emotion that has no entry here.
 */
import type { AnimalSpriteId } from '../../data/characters';
import type { AnimalEmotion, EmotionSheet } from './animalEmotions';

export const EMOTION_SHEETS: Partial<
  Record<AnimalSpriteId, Partial<Record<AnimalEmotion, EmotionSheet>>>
> = {
  'donkey-grey': {
    angry: {
      file: 'donkey-grey-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.0584,
      originX: 0.5384,
      originY: 0.7933,
    },
    doubtful: {
      file: 'donkey-grey-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.0268,
      originX: 0.5332,
      originY: 0.7922,
    },
    sneaky: {
      file: 'donkey-grey-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.177,
      originX: 0.5266,
      originY: 0.7884,
    },
    talking: {
      file: 'donkey-grey-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.1331,
      originX: 0.5361,
      originY: 0.7894,
    },
    thinking: {
      file: 'donkey-grey-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.0584,
      originX: 0.5257,
      originY: 0.7933,
    },
  },
  fox: {
    angry: {
      file: 'fox-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.3155,
      originX: 0.5723,
      originY: 0.7265,
    },
    doubtful: {
      file: 'fox-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.3018,
      originX: 0.5472,
      originY: 0.7269,
    },
    sneaky: {
      file: 'fox-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.3018,
      originX: 0.5443,
      originY: 0.7269,
    },
    talking: {
      file: 'fox-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.2616,
      originX: 0.545,
      originY: 0.7299,
    },
    thinking: {
      file: 'fox-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.3155,
      originX: 0.5635,
      originY: 0.7265,
    },
  },
  owl: {
    angry: {
      file: 'owl-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.2129,
      originX: 0.5019,
      originY: 0.75,
    },
    doubtful: {
      file: 'owl-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.1476,
      originX: 0.4931,
      originY: 0.75,
    },
    sneaky: {
      file: 'owl-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.2045,
      originX: 0.4999,
      originY: 0.75,
    },
    talking: {
      file: 'owl-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.1962,
      originX: 0.5009,
      originY: 0.75,
    },
    thinking: {
      file: 'owl-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.2299,
      originX: 0.4901,
      originY: 0.752,
    },
  },
  'white-sheep-1': {
    angry: {
      file: 'white-sheep-1-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.0861,
      originX: 0.4797,
      originY: 0.8156,
    },
    doubtful: {
      file: 'white-sheep-1-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1937,
      originX: 0.4848,
      originY: 0.8065,
    },
    sneaky: {
      file: 'white-sheep-1-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1373,
      originX: 0.4901,
      originY: 0.811,
    },
    talking: {
      file: 'white-sheep-1-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1472,
      originX: 0.4911,
      originY: 0.8121,
    },
    thinking: {
      file: 'white-sheep-1-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1937,
      originX: 0.4887,
      originY: 0.8084,
    },
  },
};
