/**
 * GENERATED FILE — do not edit by hand.
 *
 * Written by `npm run sprites:emotions -- --promote`. Lists the emotion clips that actually
 * exist on disk under `public/assets/characters/emotions/`; regenerate rather than editing,
 * or the next promote will overwrite your change.
 *
 * A committed generated module rather than a JSON file fetched at runtime, for two reasons:
 * Phaser's loader would need a second pass (read the index, then queue the sheets it names),
 * and a TS module gets the animal ids and emotion names type-checked against
 * `AnimalSpriteId` / `AnimalEmotion` at build time instead of failing silently at runtime.
 *
 * Empty is a valid state: every consumer falls back to the base `idle`/`alert` behaviour for
 * an animal or emotion that has no entry here.
 */
import type { AnimalSpriteId } from '../../data/characters';
import type { AnimalEmotion, EmotionSheet } from './animalEmotions';

export const EMOTION_SHEETS: Partial<
  Record<AnimalSpriteId, Partial<Record<AnimalEmotion, EmotionSheet>>>
> = {
  'brown-wolf': {
    angry: {
      file: 'brown-wolf-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.125,
      originX: 0.528,
      originY: 0.7012,
      quality: {
        loopPop: 0.12,
        heightSwing: 5.1,
        driftX: 0.3,
        warnings: [],
      },
    },
    doubtful: {
      file: 'brown-wolf-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.2174,
      originX: 0.521,
      originY: 0.7012,
      quality: {
        loopPop: 0.13,
        heightSwing: 12.1,
        driftX: 2.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'brown-wolf-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.1857,
      originX: 0.536,
      originY: 0.6992,
      quality: {
        loopPop: 0.33,
        heightSwing: 16.7,
        driftX: 3,
        warnings: [],
      },
    },
    talking: {
      file: 'brown-wolf-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.2174,
      originX: 0.5337,
      originY: 0.6992,
      quality: {
        loopPop: 0.28,
        heightSwing: 4.3,
        driftX: 8.5,
        warnings: [],
      },
    },
    thinking: {
      file: 'brown-wolf-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.2282,
      originX: 0.5277,
      originY: 0.7012,
      quality: {
        loopPop: 0.19,
        heightSwing: 3.4,
        driftX: 1.3,
        warnings: [],
      },
    },
  },
  'donkey-grey': {
    angry: {
      file: 'donkey-grey-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.0584,
      originX: 0.5384,
      originY: 0.7383,
    },
    doubtful: {
      file: 'donkey-grey-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.0268,
      originX: 0.5332,
      originY: 0.7363,
    },
    sneaky: {
      file: 'donkey-grey-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.177,
      originX: 0.5266,
      originY: 0.7363,
    },
    talking: {
      file: 'donkey-grey-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.1331,
      originX: 0.5361,
      originY: 0.7363,
    },
    thinking: {
      file: 'donkey-grey-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.0584,
      originX: 0.5257,
      originY: 0.7383,
    },
  },
  fox: {
    angry: {
      file: 'fox-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.3155,
      originX: 0.5723,
      originY: 0.6641,
      quality: {
        loopPop: 0.19,
        heightSwing: 32.1,
        driftX: 10.8,
        warnings: [
          'height swing 32% (over 20%) — check it is motion, not the character changing pose',
        ],
      },
    },
    doubtful: {
      file: 'fox-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.3018,
      originX: 0.5472,
      originY: 0.6641,
      quality: {
        loopPop: 0.16,
        heightSwing: 15.4,
        driftX: 6,
        warnings: [],
      },
    },
    sneaky: {
      file: 'fox-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.3018,
      originX: 0.5443,
      originY: 0.6641,
      quality: {
        loopPop: 0.19,
        heightSwing: 16.6,
        driftX: 8,
        warnings: [],
      },
    },
    talking: {
      file: 'fox-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.2616,
      originX: 0.545,
      originY: 0.666,
      quality: {
        loopPop: 0.2,
        heightSwing: 3.5,
        driftX: 1.8,
        warnings: [],
      },
    },
    thinking: {
      file: 'fox-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.3155,
      originX: 0.5635,
      originY: 0.6641,
      quality: {
        loopPop: 0.17,
        heightSwing: 14.3,
        driftX: 7.3,
        warnings: [],
      },
    },
  },
  owl: {
    angry: {
      file: 'owl-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.2129,
      originX: 0.5019,
      originY: 0.75,
    },
    doubtful: {
      file: 'owl-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.1476,
      originX: 0.4931,
      originY: 0.75,
    },
    sneaky: {
      file: 'owl-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.2045,
      originX: 0.4999,
      originY: 0.75,
    },
    talking: {
      file: 'owl-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.1962,
      originX: 0.5009,
      originY: 0.75,
    },
    thinking: {
      file: 'owl-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 16,
      frameRate: 8,
      scale: 2.2299,
      originX: 0.4901,
      originY: 0.752,
    },
  },
  raccoon: {
    angry: {
      file: 'raccoon-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.4663,
      originX: 0.5123,
      originY: 0.6855,
      quality: {
        loopPop: 0.16,
        heightSwing: 13,
        driftX: 11.5,
        warnings: [],
      },
    },
    doubtful: {
      file: 'raccoon-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.4198,
      originX: 0.5115,
      originY: 0.6836,
      quality: {
        loopPop: 0.17,
        heightSwing: 10.9,
        driftX: 11.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'raccoon-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.7,
      originX: 0.5112,
      originY: 0.6836,
      quality: {
        loopPop: 0.17,
        heightSwing: 3.7,
        driftX: 1.3,
        warnings: [],
      },
    },
    talking: {
      file: 'raccoon-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.5779,
      originX: 0.5117,
      originY: 0.6836,
      quality: {
        loopPop: 0.16,
        heightSwing: 5.5,
        driftX: 1.8,
        warnings: [],
      },
    },
    thinking: {
      file: 'raccoon-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.565,
      originX: 0.5118,
      originY: 0.6836,
      quality: {
        loopPop: 0.17,
        heightSwing: 6,
        driftX: 5.8,
        warnings: [],
      },
    },
  },
  'white-sheep-1': {
    angry: {
      file: 'white-sheep-1-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.0861,
      originX: 0.4797,
      originY: 0.7148,
      quality: {
        loopPop: 0.31,
        heightSwing: 18.5,
        driftX: 3.5,
        warnings: [],
      },
    },
    doubtful: {
      file: 'white-sheep-1-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1937,
      originX: 0.4848,
      originY: 0.7148,
      quality: {
        loopPop: 0.28,
        heightSwing: 7.7,
        driftX: 4,
        warnings: [],
      },
    },
    sneaky: {
      file: 'white-sheep-1-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1373,
      originX: 0.4901,
      originY: 0.7148,
      quality: {
        loopPop: 0.31,
        heightSwing: 5.2,
        driftX: 1.8,
        warnings: [],
      },
    },
    talking: {
      file: 'white-sheep-1-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1472,
      originX: 0.4911,
      originY: 0.7168,
      quality: {
        loopPop: 0.32,
        heightSwing: 7.4,
        driftX: 2.5,
        warnings: [],
      },
    },
    thinking: {
      file: 'white-sheep-1-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1937,
      originX: 0.4887,
      originY: 0.7168,
      quality: {
        loopPop: 0.29,
        heightSwing: 2.7,
        driftX: 4,
        warnings: [],
      },
    },
  },
};
