/**
 * GENERATED FILE — do not edit by hand.
 *
 * Written by `npm run sprites:emotions -- --promote`. Lists the emotion clips that actually
 * exist on disk under `public/assets/characters/emotions/`; regenerate rather than editing,
 * or the next promote will overwrite your change.
 *
 * A committed generated module rather than a JSON file fetched at runtime, for two reasons:
 * Phaser's loader would need a second pass (read the index, then queue the sheets it names),
 * and a TS module gets the animal ids and emotion names type-checked against
 * `AnimalSpriteId` / `AnimalEmotion` at build time instead of failing silently at runtime.
 *
 * Empty is a valid state: every consumer falls back to the base `idle`/`alert` behaviour for
 * an animal or emotion that has no entry here.
 */
import type { AnimalSpriteId } from '../../data/characters';
import type { AnimalEmotion, EmotionSheet } from './animalEmotions';

export const EMOTION_SHEETS: Partial<
  Record<AnimalSpriteId, Partial<Record<AnimalEmotion, EmotionSheet>>>
> = {
  'brown-bull': {
    angry: {
      file: 'brown-bull-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 3.3529,
      originX: 0.497,
      originY: 0.6992,
      quality: {
        loopPop: 0.16,
        heightSwing: 13.7,
        driftX: 1,
        warnings: [],
      },
    },
    doubtful: {
      file: 'brown-bull-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 3.3204,
      originX: 0.5048,
      originY: 0.6992,
      quality: {
        loopPop: 0.12,
        heightSwing: 1.5,
        driftX: 3.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'brown-bull-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 3.1963,
      originX: 0.4969,
      originY: 0.6973,
      quality: {
        loopPop: 0.2,
        heightSwing: 5.1,
        driftX: 2.3,
        warnings: [],
      },
    },
    talking: {
      file: 'brown-bull-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 3.3204,
      originX: 0.495,
      originY: 0.6973,
      quality: {
        loopPop: 0.19,
        heightSwing: 1.5,
        driftX: 1,
        warnings: [],
      },
    },
    thinking: {
      file: 'brown-bull-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 3.2264,
      originX: 0.5076,
      originY: 0.6973,
      quality: {
        loopPop: 0.16,
        heightSwing: 4.7,
        driftX: 4,
        warnings: [],
      },
    },
  },
  'brown-wolf': {
    angry: {
      file: 'brown-wolf-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.125,
      originX: 0.528,
      originY: 0.7012,
      quality: {
        loopPop: 0.12,
        heightSwing: 5.1,
        driftX: 0.3,
        warnings: [],
      },
    },
    doubtful: {
      file: 'brown-wolf-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.2174,
      originX: 0.521,
      originY: 0.7012,
      quality: {
        loopPop: 0.13,
        heightSwing: 12.1,
        driftX: 2.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'brown-wolf-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.1857,
      originX: 0.536,
      originY: 0.6992,
      quality: {
        loopPop: 0.33,
        heightSwing: 16.7,
        driftX: 3,
        warnings: [],
      },
    },
    talking: {
      file: 'brown-wolf-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.2174,
      originX: 0.5337,
      originY: 0.6992,
      quality: {
        loopPop: 0.28,
        heightSwing: 4.3,
        driftX: 8.5,
        warnings: [],
      },
    },
    thinking: {
      file: 'brown-wolf-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.2282,
      originX: 0.5277,
      originY: 0.7012,
      quality: {
        loopPop: 0.19,
        heightSwing: 3.4,
        driftX: 1.3,
        warnings: [],
      },
    },
  },
  cow: {
    angry: {
      file: 'cow-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 1.7887,
      originX: 0.4855,
      originY: 0.6992,
      quality: {
        loopPop: 0.36,
        heightSwing: 7.5,
        driftX: 2.3,
        warnings: [],
      },
    },
    approving: {
      file: 'cow-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.7558,
      originX: 0.4861,
      originY: 0.7012,
      quality: {
        loopPop: 0.29,
        heightSwing: 6,
        driftX: 2.8,
        warnings: [],
      },
    },
    doubtful: {
      file: 'cow-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.8406,
      originX: 0.5006,
      originY: 0.7012,
      quality: {
        loopPop: 0.34,
        heightSwing: 11.7,
        driftX: 9.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'cow-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 1.8406,
      originX: 0.4703,
      originY: 0.6992,
      quality: {
        loopPop: 0.36,
        heightSwing: 9.2,
        driftX: 5.5,
        warnings: [],
      },
    },
    talking: {
      file: 'cow-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 12.5,
      scale: 1.9538,
      originX: 0.484,
      originY: 0.6797,
      quality: {
        loopPop: 0.22,
        heightSwing: 6.7,
        driftX: 2,
        warnings: [],
      },
    },
  },
  dog: {
    angry: {
      file: 'dog-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.7212,
      originX: 0.5041,
      originY: 0.7031,
      quality: {
        loopPop: 0.12,
        heightSwing: 13,
        driftX: 2,
        warnings: [],
      },
    },
    doubtful: {
      file: 'dog-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.7212,
      originX: 0.4963,
      originY: 0.7031,
      quality: {
        loopPop: 0.12,
        heightSwing: 12,
        driftX: 1.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'dog-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.7212,
      originX: 0.5099,
      originY: 0.7031,
      quality: {
        loopPop: 0.13,
        heightSwing: 1,
        driftX: 3,
        warnings: [],
      },
    },
    talking: {
      file: 'dog-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.7212,
      originX: 0.505,
      originY: 0.7031,
      quality: {
        loopPop: 0.11,
        heightSwing: 4.3,
        driftX: 3.5,
        warnings: [],
      },
    },
    thinking: {
      file: 'dog-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.7081,
      originX: 0.5246,
      originY: 0.7031,
      quality: {
        loopPop: 0.3,
        heightSwing: 12.9,
        driftX: 8.5,
        warnings: [],
      },
    },
  },
  'donkey-grey': {
    angry: {
      file: 'donkey-grey-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.168,
      originX: 0.515,
      originY: 0.7363,
      quality: {
        loopPop: 0.27,
        heightSwing: 18.4,
        driftX: 6,
        warnings: [],
      },
    },
    doubtful: {
      file: 'donkey-grey-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.177,
      originX: 0.5041,
      originY: 0.7363,
      quality: {
        loopPop: 0.18,
        heightSwing: 7.4,
        driftX: 10.8,
        warnings: [],
      },
    },
    sneaky: {
      file: 'donkey-grey-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.1245,
      originX: 0.5324,
      originY: 0.7363,
      quality: {
        loopPop: 0.17,
        heightSwing: 3.2,
        driftX: 2.8,
        warnings: [],
      },
    },
    talking: {
      file: 'donkey-grey-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.1331,
      originX: 0.5342,
      originY: 0.7363,
      quality: {
        loopPop: 0.21,
        heightSwing: 2,
        driftX: 3.3,
        warnings: [],
      },
    },
    thinking: {
      file: 'donkey-grey-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.168,
      originX: 0.5345,
      originY: 0.7363,
      quality: {
        loopPop: 0.27,
        heightSwing: 2,
        driftX: 1.8,
        warnings: [],
      },
    },
  },
  fox: {
    angry: {
      file: 'fox-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.2486,
      originX: 0.5638,
      originY: 0.6641,
      quality: {
        loopPop: 0.2,
        heightSwing: 12.9,
        driftX: 10.5,
        warnings: [],
      },
    },
    doubtful: {
      file: 'fox-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.3018,
      originX: 0.5443,
      originY: 0.6641,
      quality: {
        loopPop: 0.16,
        heightSwing: 10.1,
        driftX: 1,
        warnings: [],
      },
    },
    sneaky: {
      file: 'fox-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.3018,
      originX: 0.5443,
      originY: 0.6641,
      quality: {
        loopPop: 0.19,
        heightSwing: 16.6,
        driftX: 8,
        warnings: [],
      },
    },
    talking: {
      file: 'fox-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.2229,
      originX: 0.535,
      originY: 0.6641,
      quality: {
        loopPop: 0.18,
        heightSwing: 16,
        driftX: 2.5,
        warnings: [],
      },
    },
    thinking: {
      file: 'fox-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.2882,
      originX: 0.5552,
      originY: 0.6641,
      quality: {
        loopPop: 0.17,
        heightSwing: 1.8,
        driftX: 3.5,
        warnings: [],
      },
    },
  },
  mouse: {
    angry: {
      file: 'mouse-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.8193,
      originX: 0.5048,
      originY: 0.6621,
      quality: {
        loopPop: 0.17,
        heightSwing: 1.8,
        driftX: 1.8,
        warnings: [],
      },
    },
    doubtful: {
      file: 'mouse-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.6441,
      originX: 0.4904,
      originY: 0.6602,
      quality: {
        loopPop: 0.23,
        heightSwing: 7.9,
        driftX: 15.5,
        warnings: [],
      },
    },
    sneaky: {
      file: 'mouse-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.8024,
      originX: 0.4999,
      originY: 0.6602,
      quality: {
        loopPop: 0.18,
        heightSwing: 3.6,
        driftX: 4,
        warnings: [],
      },
    },
    talking: {
      file: 'mouse-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.7209,
      originX: 0.4961,
      originY: 0.6602,
      quality: {
        loopPop: 0.18,
        heightSwing: 4.7,
        driftX: 3.8,
        warnings: [],
      },
    },
    thinking: {
      file: 'mouse-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.8024,
      originX: 0.5029,
      originY: 0.6602,
      quality: {
        loopPop: 0.21,
        heightSwing: 1.8,
        driftX: 0.8,
        warnings: [],
      },
    },
  },
  owl: {
    angry: {
      file: 'owl-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.1962,
      originX: 0.5019,
      originY: 0.75,
      quality: {
        loopPop: 0.1,
        heightSwing: 7.6,
        driftX: 0.3,
        warnings: [],
      },
    },
    approving: {
      file: 'owl-approving.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.1556,
      originX: 0.5107,
      originY: 0.75,
      quality: {
        loopPop: 0.14,
        heightSwing: 6.3,
        driftX: 5.5,
        warnings: [],
      },
    },
    doubtful: {
      file: 'owl-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.2214,
      originX: 0.496,
      originY: 0.75,
      quality: {
        loopPop: 0.43,
        heightSwing: 9.2,
        driftX: 2.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'owl-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.1087,
      originX: 0.5058,
      originY: 0.75,
      quality: {
        loopPop: 0.12,
        heightSwing: 7.2,
        driftX: 3.8,
        warnings: [],
      },
    },
    talking: {
      file: 'owl-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.1716,
      originX: 0.5009,
      originY: 0.75,
      quality: {
        loopPop: 0.14,
        heightSwing: 6,
        driftX: 0,
        warnings: [],
      },
    },
    thinking: {
      file: 'owl-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.2299,
      originX: 0.4921,
      originY: 0.748,
      quality: {
        loopPop: 0.13,
        heightSwing: 1.9,
        driftX: 3,
        warnings: [],
      },
    },
  },
  pig: {
    angry: {
      file: 'pig-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 1.6214,
      originX: 0.4949,
      originY: 0.6348,
      quality: {
        loopPop: 0.31,
        heightSwing: 5.7,
        driftX: 1.5,
        warnings: [],
      },
    },
    doubtful: {
      file: 'pig-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.6099,
      originX: 0.4968,
      originY: 0.6367,
      quality: {
        loopPop: 0.21,
        heightSwing: 3.5,
        driftX: 2,
        warnings: [],
      },
    },
    talking: {
      file: 'pig-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.5986,
      originX: 0.4958,
      originY: 0.6387,
      quality: {
        loopPop: 0.25,
        heightSwing: 1.4,
        driftX: 2,
        warnings: [],
      },
    },
    thinking: {
      file: 'pig-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.5986,
      originX: 0.5017,
      originY: 0.6387,
      quality: {
        loopPop: 0.25,
        heightSwing: 1.4,
        driftX: 4,
        warnings: [],
      },
    },
  },
  raccoon: {
    angry: {
      file: 'raccoon-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.4663,
      originX: 0.5123,
      originY: 0.6855,
      quality: {
        loopPop: 0.16,
        heightSwing: 13,
        driftX: 11.5,
        warnings: [],
      },
    },
    doubtful: {
      file: 'raccoon-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.4198,
      originX: 0.5115,
      originY: 0.6836,
      quality: {
        loopPop: 0.17,
        heightSwing: 10.9,
        driftX: 11.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'raccoon-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.7,
      originX: 0.5112,
      originY: 0.6836,
      quality: {
        loopPop: 0.17,
        heightSwing: 3.7,
        driftX: 1.3,
        warnings: [],
      },
    },
    talking: {
      file: 'raccoon-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.5779,
      originX: 0.5117,
      originY: 0.6836,
      quality: {
        loopPop: 0.16,
        heightSwing: 5.5,
        driftX: 1.8,
        warnings: [],
      },
    },
    thinking: {
      file: 'raccoon-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.565,
      originX: 0.5118,
      originY: 0.6836,
      quality: {
        loopPop: 0.17,
        heightSwing: 6,
        driftX: 5.8,
        warnings: [],
      },
    },
  },
  seagull: {
    angry: {
      file: 'seagull-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.9261,
      originX: 0.547,
      originY: 0.75,
      quality: {
        loopPop: 0.09,
        heightSwing: 0.8,
        driftX: 2.3,
        warnings: [],
      },
    },
    doubtful: {
      file: 'seagull-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.9035,
      originX: 0.5552,
      originY: 0.748,
      quality: {
        loopPop: 0.6,
        heightSwing: 2.3,
        driftX: 2.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'seagull-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.9261,
      originX: 0.5528,
      originY: 0.748,
      quality: {
        loopPop: 0.11,
        heightSwing: 1.2,
        driftX: 2,
        warnings: [],
      },
    },
    talking: {
      file: 'seagull-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.9375,
      originX: 0.5526,
      originY: 0.748,
      quality: {
        loopPop: 0.19,
        heightSwing: 2,
        driftX: 1.3,
        warnings: [],
      },
    },
    thinking: {
      file: 'seagull-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.9375,
      originX: 0.5555,
      originY: 0.748,
      quality: {
        loopPop: 0.1,
        heightSwing: 0,
        driftX: 0.5,
        warnings: [],
      },
    },
  },
  skunk: {
    angry: {
      file: 'skunk-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.5446,
      originX: 0.5175,
      originY: 0.5938,
      quality: {
        loopPop: 0.12,
        heightSwing: 7,
        driftX: 0.8,
        warnings: [],
      },
    },
    doubtful: {
      file: 'skunk-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.6771,
      originX: 0.5157,
      originY: 0.5938,
      quality: {
        loopPop: 0.16,
        heightSwing: 2.1,
        driftX: 0.5,
        warnings: [],
      },
    },
    sneaky: {
      file: 'skunk-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.6495,
      originX: 0.5198,
      originY: 0.5918,
      quality: {
        loopPop: 0.18,
        heightSwing: 4.1,
        driftX: 3,
        warnings: [],
      },
    },
    talking: {
      file: 'skunk-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.6495,
      originX: 0.5188,
      originY: 0.5918,
      quality: {
        loopPop: 0.16,
        heightSwing: 3.1,
        driftX: 2.3,
        warnings: [],
      },
    },
    thinking: {
      file: 'skunk-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.6224,
      originX: 0.516,
      originY: 0.5918,
      quality: {
        loopPop: 0.18,
        heightSwing: 3.1,
        driftX: 0.5,
        warnings: [],
      },
    },
  },
  snake: {
    angry: {
      file: 'snake-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 3.513,
      originX: 0.4573,
      originY: 0.6094,
      quality: {
        loopPop: 0.07,
        heightSwing: 3.5,
        driftX: 0.3,
        warnings: [],
      },
    },
    doubtful: {
      file: 'snake-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 3.6071,
      originX: 0.4594,
      originY: 0.6094,
      quality: {
        loopPop: 0.04,
        heightSwing: 2.7,
        driftX: 0,
        warnings: [],
      },
    },
    sneaky: {
      file: 'snake-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 3.513,
      originX: 0.4573,
      originY: 0.6094,
      quality: {
        loopPop: 0.04,
        heightSwing: 10.4,
        driftX: 0.3,
        warnings: [],
      },
    },
    talking: {
      file: 'snake-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 3.2846,
      originX: 0.4554,
      originY: 0.6094,
      quality: {
        loopPop: 0.17,
        heightSwing: 8.9,
        driftX: 0.5,
        warnings: [],
      },
    },
    thinking: {
      file: 'snake-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 3.6071,
      originX: 0.4594,
      originY: 0.6094,
      quality: {
        loopPop: 0.04,
        heightSwing: 0,
        driftX: 0,
        warnings: [],
      },
    },
  },
  'white-chicken': {
    angry: {
      file: 'white-chicken-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.249,
      originX: 0.409,
      originY: 0.75,
      quality: {
        loopPop: 0.24,
        heightSwing: 4.2,
        driftX: 4,
        warnings: [],
      },
    },
    doubtful: {
      file: 'white-chicken-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.284,
      originX: 0.4162,
      originY: 0.75,
      quality: {
        loopPop: 0.22,
        heightSwing: 1.2,
        driftX: 1.5,
        warnings: [],
      },
    },
    sneaky: {
      file: 'white-chicken-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 2.2752,
      originX: 0.4159,
      originY: 0.752,
      quality: {
        loopPop: 0.25,
        heightSwing: 0.4,
        driftX: 0.5,
        warnings: [],
      },
    },
    talking: {
      file: 'white-chicken-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.284,
      originX: 0.4133,
      originY: 0.752,
      quality: {
        loopPop: 0.25,
        heightSwing: 0.4,
        driftX: 1,
        warnings: [],
      },
    },
    thinking: {
      file: 'white-chicken-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 2.284,
      originX: 0.4172,
      originY: 0.75,
      quality: {
        loopPop: 0.23,
        heightSwing: 0.8,
        driftX: 0.3,
        warnings: [],
      },
    },
  },
  'white-sheep-1': {
    angry: {
      file: 'white-sheep-1-angry.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 36,
      frameRate: 12,
      scale: 1.1572,
      originX: 0.4746,
      originY: 0.7324,
      quality: {
        loopPop: 1.15,
        heightSwing: 5.3,
        driftX: 2,
        warnings: [],
      },
      phases: {
        in: {
          file: 'white-sheep-1-angry.png',
          frameWidth: 512,
          frameHeight: 512,
          frameCount: 24,
          startFrame: 0,
          frameRate: 12,
          scale: 1.1572,
          originX: 0.4746,
          originY: 0.7324,
          quality: {
            loopPop: 1.89,
            heightSwing: 5.3,
            driftX: 2,
            seamOut: 0.46,
            warnings: [],
          },
        },
        loop: {
          file: 'white-sheep-1-angry-loop.png',
          frameWidth: 512,
          frameHeight: 512,
          frameCount: 36,
          frameRate: 12,
          scale: 1.1313,
          originX: 0.493,
          originY: 0.7188,
          quality: {
            loopPop: 0.42,
            heightSwing: 5.8,
            driftX: 2.5,
            seamIn: 0.46,
            seamOut: 0.47,
            warnings: [],
          },
        },
        out: {
          file: 'white-sheep-1-angry-out.png',
          frameWidth: 512,
          frameHeight: 512,
          frameCount: 21,
          frameRate: 12,
          scale: 1.1313,
          originX: 0.4901,
          originY: 0.7286,
          quality: {
            loopPop: 1.62,
            heightSwing: 3.5,
            driftX: 1.3,
            seamIn: 0.47,
            seamOut: 1.16,
            warnings: [],
          },
        },
      },
    },
    doubtful: {
      file: 'white-sheep-1-doubtful.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1937,
      originX: 0.4848,
      originY: 0.7148,
      quality: {
        loopPop: 0.28,
        heightSwing: 7.7,
        driftX: 4,
        warnings: [],
      },
    },
    sneaky: {
      file: 'white-sheep-1-sneaky.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1373,
      originX: 0.4901,
      originY: 0.7148,
      quality: {
        loopPop: 0.31,
        heightSwing: 5.2,
        driftX: 1.8,
        warnings: [],
      },
    },
    talking: {
      file: 'white-sheep-1-talking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1472,
      originX: 0.4911,
      originY: 0.7168,
      quality: {
        loopPop: 0.32,
        heightSwing: 7.4,
        driftX: 2.5,
        warnings: [],
      },
    },
    thinking: {
      file: 'white-sheep-1-thinking.png',
      frameWidth: 512,
      frameHeight: 512,
      frameCount: 25,
      frameRate: 13,
      scale: 1.1937,
      originX: 0.4887,
      originY: 0.7168,
      quality: {
        loopPop: 0.29,
        heightSwing: 2.7,
        driftX: 4,
        warnings: [],
      },
    },
  },
};
