/**
 * GENERATED FILE — do not edit by hand.
 *
 * Written by `npm run sprites:emotions -- --faces --promote`. Lists the headshot clips that
 * actually exist on disk under `public/assets/characters/faces/`; regenerate rather than
 * editing, or the next promote will overwrite your change.
 *
 * The face register's counterpart to `emotionSheets.generated.ts`, and deliberately a
 * separate module rather than a second export from it: the two are promoted independently
 * from independent records, and a face sheet is not a drop-in for a body sheet — it carries
 * `cols` and `fit` where a body clip carries `scale` and a feet origin, because one is
 * centred in a DOM portrait box and the other is planted on a Phaser floor line. Separate
 * types make handing one to the other's code a compile error rather than a sprite rendered
 * 3x too small.
 *
 * Empty is a valid state: a character with no entry here simply shows no portrait, exactly as
 * an animal with no emotion clip falls back to its idle loop.
 */
import type { AnimalSpriteId } from '../../data/characters';
import type { AnimalEmotion } from './animalEmotions';
import type { FaceSheet } from './animalFaces';

export const FACE_SHEETS: Partial<
  Record<AnimalSpriteId, Partial<Record<AnimalEmotion, FaceSheet>>>
> = {
  'brown-wolf': {
    angry: {
      file: 'brown-wolf-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0259, y: 0, width: 0.9483, height: 1 },
      quality: {
        loopPop: 0.49,
        heightSwing: 8.6,
        driftX: 2.8,
        warnings: [],
      },
    },
    doubtful: {
      file: 'brown-wolf-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0259, y: 0, width: 0.9483, height: 1 },
      quality: {
        loopPop: 0.53,
        heightSwing: 13.3,
        driftX: 7.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'brown-wolf-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0259, y: 0, width: 0.9483, height: 1 },
      quality: {
        loopPop: 1.64,
        heightSwing: 12,
        driftX: 5.3,
        warnings: [],
      },
    },
    talking: {
      file: 'brown-wolf-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0259, y: 0, width: 0.9483, height: 1 },
      quality: {
        loopPop: 1.83,
        heightSwing: 4,
        driftX: 10.8,
        warnings: [],
      },
    },
    thinking: {
      file: 'brown-wolf-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0259, y: 0, width: 0.9483, height: 1 },
      quality: {
        loopPop: 1.55,
        heightSwing: 7.8,
        driftX: 7,
        warnings: [],
      },
    },
  },
  dog: {
    angry: {
      file: 'dog-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0172, y: 0, width: 0.9655, height: 1 },
      quality: {
        loopPop: 1.34,
        heightSwing: 5.2,
        driftX: 3,
        warnings: [],
      },
    },
    doubtful: {
      file: 'dog-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0172, y: 0, width: 0.9655, height: 1 },
      quality: {
        loopPop: 0.51,
        heightSwing: 9.3,
        driftX: 6.5,
        warnings: [],
      },
    },
    talking: {
      file: 'dog-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0172, y: 0, width: 0.9655, height: 1 },
      quality: {
        loopPop: 0.47,
        heightSwing: 5.7,
        driftX: 3,
        warnings: [],
      },
    },
    thinking: {
      file: 'dog-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0172, y: 0, width: 0.9655, height: 1 },
      quality: {
        loopPop: 1.68,
        heightSwing: 8.9,
        driftX: 5.3,
        warnings: [],
      },
    },
  },
  'donkey-grey': {
    angry: {
      file: 'donkey-grey-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 16,
      frameRate: 8,
      cols: 4,
      fit: { x: 0.1087, y: 0, width: 0.7826, height: 1 },
      quality: {
        loopPop: 0.57,
        heightSwing: 9.2,
        driftX: 12.5,
        warnings: [],
      },
    },
    sneaky: {
      file: 'donkey-grey-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 16,
      frameRate: 8,
      cols: 4,
      fit: { x: 0.1087, y: 0, width: 0.7826, height: 1 },
      quality: {
        loopPop: 0.54,
        heightSwing: 33.6,
        driftX: 14.3,
        warnings: [],
      },
    },
    talking: {
      file: 'donkey-grey-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.1087, y: 0, width: 0.7826, height: 1 },
      quality: {
        loopPop: 0.56,
        heightSwing: 3.3,
        driftX: 6.8,
        warnings: [],
      },
    },
  },
  fox: {
    angry: {
      file: 'fox-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0455, width: 1, height: 0.9091 },
      quality: {
        loopPop: 0.91,
        heightSwing: 6.4,
        driftX: 6,
        warnings: [],
      },
    },
    doubtful: {
      file: 'fox-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0455, width: 1, height: 0.9091 },
      quality: {
        loopPop: 0.68,
        heightSwing: 8.5,
        driftX: 2,
        warnings: [],
      },
    },
    sneaky: {
      file: 'fox-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0455, width: 1, height: 0.9091 },
      quality: {
        loopPop: 0.9,
        heightSwing: 12.6,
        driftX: 11,
        warnings: [],
      },
    },
    talking: {
      file: 'fox-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0455, width: 1, height: 0.9091 },
      quality: {
        loopPop: 0.93,
        heightSwing: 10.8,
        driftX: 3.8,
        warnings: [],
      },
    },
    thinking: {
      file: 'fox-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0455, width: 1, height: 0.9091 },
      quality: {
        loopPop: 0.73,
        heightSwing: 16.4,
        driftX: 9.8,
        warnings: [],
      },
    },
  },
  owl: {
    angry: {
      file: 'owl-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 0.27,
        heightSwing: 1.8,
        driftX: 0.5,
        warnings: [],
      },
    },
    approving: {
      file: 'owl-approving.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 1.31,
        heightSwing: 5.1,
        driftX: 2,
        warnings: [],
      },
    },
    doubtful: {
      file: 'owl-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 0.77,
        heightSwing: 8.6,
        driftX: 1,
        warnings: [],
      },
    },
    sneaky: {
      file: 'owl-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 0.38,
        heightSwing: 4.1,
        driftX: 4,
        warnings: [],
      },
    },
    talking: {
      file: 'owl-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 0.55,
        heightSwing: 5.2,
        driftX: 0.3,
        warnings: [],
      },
    },
    thinking: {
      file: 'owl-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 0.47,
        heightSwing: 2.9,
        driftX: 3,
        warnings: [],
      },
    },
  },
  raccoon: {
    angry: {
      file: 'raccoon-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1275, width: 1, height: 0.745 },
      quality: {
        loopPop: 0.59,
        heightSwing: 6.4,
        driftX: 7,
        warnings: [],
      },
    },
    doubtful: {
      file: 'raccoon-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1275, width: 1, height: 0.745 },
      quality: {
        loopPop: 0.66,
        heightSwing: 2.4,
        driftX: 3.5,
        warnings: [],
      },
    },
    sneaky: {
      file: 'raccoon-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1275, width: 1, height: 0.745 },
      quality: {
        loopPop: 0.62,
        heightSwing: 5.3,
        driftX: 5.5,
        warnings: [],
      },
    },
    talking: {
      file: 'raccoon-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1275, width: 1, height: 0.745 },
      quality: {
        loopPop: 0.55,
        heightSwing: 2.9,
        driftX: 3.8,
        warnings: [],
      },
    },
    thinking: {
      file: 'raccoon-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1275, width: 1, height: 0.745 },
      quality: {
        loopPop: 0.62,
        heightSwing: 1.2,
        driftX: 0.8,
        warnings: [],
      },
    },
  },
  'white-sheep-1': {
    angry: {
      file: 'white-sheep-1-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.015, width: 1, height: 0.9699 },
      quality: {
        loopPop: 1.46,
        heightSwing: 11.7,
        driftX: 13.8,
        warnings: [],
      },
    },
    doubtful: {
      file: 'white-sheep-1-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.015, width: 1, height: 0.9699 },
      quality: {
        loopPop: 1.31,
        heightSwing: 10,
        driftX: 13,
        warnings: [],
      },
    },
    sneaky: {
      file: 'white-sheep-1-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.015, width: 1, height: 0.9699 },
      quality: {
        loopPop: 1.23,
        heightSwing: 2.6,
        driftX: 1.5,
        warnings: [],
      },
    },
    talking: {
      file: 'white-sheep-1-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.015, width: 1, height: 0.9699 },
      quality: {
        loopPop: 0.76,
        heightSwing: 2.6,
        driftX: 6.3,
        warnings: [],
      },
    },
    thinking: {
      file: 'white-sheep-1-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.015, width: 1, height: 0.9699 },
      quality: {
        loopPop: 0.8,
        heightSwing: 5.2,
        driftX: 6.3,
        warnings: [],
      },
    },
  },
};
