/**
 * GENERATED FILE — do not edit by hand.
 *
 * Written by `npm run sprites:emotions -- --faces --promote`. Lists the headshot clips that
 * actually exist on disk under `public/assets/characters/faces/`; regenerate rather than
 * editing, or the next promote will overwrite your change.
 *
 * The face register's counterpart to `emotionSheets.generated.ts`, and deliberately a
 * separate module rather than a second export from it: the two are promoted independently
 * from independent records, and a face sheet is not a drop-in for a body sheet — it carries
 * `cols` and `fit` where a body clip carries `scale` and a feet origin, because one is
 * centred in a DOM portrait box and the other is planted on a Phaser floor line. Separate
 * types make handing one to the other's code a compile error rather than a sprite rendered
 * 3x too small.
 *
 * Empty is a valid state: a character with no entry here simply shows no portrait, exactly as
 * an animal with no emotion clip falls back to its idle loop.
 */
import type { AnimalSpriteId } from '../../data/characters';
import type { AnimalEmotion } from './animalEmotions';
import type { FaceSheet } from './animalFaces';

export const FACE_SHEETS: Partial<
  Record<AnimalSpriteId, Partial<Record<AnimalEmotion, FaceSheet>>>
> = {
  'brown-bull': {
    angry: {
      file: 'brown-bull-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 36,
      frameRate: 12,
      cols: 6,
      fit: { x: 0, y: 0.0199, width: 1, height: 0.9602 },
      quality: {
        loopPop: 2.26,
        heightSwing: 3.2,
        driftX: 2.3,
        warnings: ['loop seam 2.26% (over 2%) — it will visibly jump on every repeat'],
      },
    },
    doubtful: {
      file: 'brown-bull-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0199, width: 1, height: 0.9602 },
      quality: {
        loopPop: 0.63,
        heightSwing: 6.7,
        driftX: 5.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'brown-bull-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0199, width: 1, height: 0.9602 },
      quality: {
        loopPop: 0.72,
        heightSwing: 4.6,
        driftX: 1.8,
        warnings: [],
      },
    },
    talking: {
      file: 'brown-bull-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0199, width: 1, height: 0.9602 },
      quality: {
        loopPop: 0.71,
        heightSwing: 4.1,
        driftX: 1,
        warnings: [],
      },
    },
    thinking: {
      file: 'brown-bull-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0199, width: 1, height: 0.9602 },
      quality: {
        loopPop: 0.63,
        heightSwing: 3.2,
        driftX: 2.3,
        warnings: [],
      },
    },
  },
  'brown-wolf': {
    angry: {
      file: 'brown-wolf-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0259, y: 0, width: 0.9483, height: 1 },
      quality: {
        loopPop: 0.49,
        heightSwing: 8.6,
        driftX: 2.8,
        warnings: [],
      },
    },
    doubtful: {
      file: 'brown-wolf-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0259, y: 0, width: 0.9483, height: 1 },
      quality: {
        loopPop: 0.53,
        heightSwing: 13.3,
        driftX: 7.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'brown-wolf-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0259, y: 0, width: 0.9483, height: 1 },
      quality: {
        loopPop: 1.64,
        heightSwing: 12,
        driftX: 5.3,
        warnings: [],
      },
    },
    talking: {
      file: 'brown-wolf-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0259, y: 0, width: 0.9483, height: 1 },
      quality: {
        loopPop: 1.83,
        heightSwing: 4,
        driftX: 10.8,
        warnings: [],
      },
    },
    thinking: {
      file: 'brown-wolf-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0259, y: 0, width: 0.9483, height: 1 },
      quality: {
        loopPop: 1.55,
        heightSwing: 7.8,
        driftX: 7,
        warnings: [],
      },
    },
  },
  cow: {
    approving: {
      file: 'cow-approving.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0276, width: 1, height: 0.9448 },
      quality: {
        loopPop: 1.84,
        heightSwing: 10.7,
        driftX: 2.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'cow-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0276, width: 1, height: 0.9448 },
      quality: {
        loopPop: 0.79,
        heightSwing: 13.8,
        driftX: 3.8,
        warnings: [],
      },
    },
    talking: {
      file: 'cow-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 12.5,
      cols: 5,
      fit: { x: 0, y: 0.0276, width: 1, height: 0.9448 },
      quality: {
        loopPop: 0.51,
        heightSwing: 16.6,
        driftX: 9.3,
        warnings: [],
      },
    },
  },
  dog: {
    angry: {
      file: 'dog-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0172, y: 0, width: 0.9655, height: 1 },
      quality: {
        loopPop: 1.34,
        heightSwing: 5.2,
        driftX: 3,
        warnings: [],
      },
    },
    doubtful: {
      file: 'dog-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0172, y: 0, width: 0.9655, height: 1 },
      quality: {
        loopPop: 0.51,
        heightSwing: 9.3,
        driftX: 6.5,
        warnings: [],
      },
    },
    talking: {
      file: 'dog-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0172, y: 0, width: 0.9655, height: 1 },
      quality: {
        loopPop: 0.47,
        heightSwing: 5.7,
        driftX: 3,
        warnings: [],
      },
    },
    thinking: {
      file: 'dog-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0172, y: 0, width: 0.9655, height: 1 },
      quality: {
        loopPop: 1.68,
        heightSwing: 8.9,
        driftX: 5.3,
        warnings: [],
      },
    },
  },
  'donkey-grey': {
    angry: {
      file: 'donkey-grey-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 36,
      frameRate: 12,
      cols: 6,
      fit: { x: 0.1148, y: 0, width: 0.7705, height: 1 },
      quality: {
        loopPop: 0.47,
        heightSwing: 14.5,
        driftX: 3.5,
        warnings: [],
      },
    },
    doubtful: {
      file: 'donkey-grey-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 36,
      frameRate: 12,
      cols: 6,
      fit: { x: 0.1148, y: 0, width: 0.7705, height: 1 },
      quality: {
        loopPop: 0.32,
        heightSwing: 23.4,
        driftX: 12.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'donkey-grey-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 36,
      frameRate: 12,
      cols: 6,
      fit: { x: 0.1148, y: 0, width: 0.7705, height: 1 },
      quality: {
        loopPop: 0.34,
        heightSwing: 7.8,
        driftX: 7.3,
        warnings: [],
      },
    },
    talking: {
      file: 'donkey-grey-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.1148, y: 0, width: 0.7705, height: 1 },
      quality: {
        loopPop: 0.46,
        heightSwing: 4.1,
        driftX: 4.8,
        warnings: [],
      },
    },
    thinking: {
      file: 'donkey-grey-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 36,
      frameRate: 12,
      cols: 6,
      fit: { x: 0.1148, y: 0, width: 0.7705, height: 1 },
      quality: {
        loopPop: 0.96,
        heightSwing: 3.8,
        driftX: 1,
        warnings: [],
      },
    },
  },
  fox: {
    angry: {
      file: 'fox-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0455, width: 1, height: 0.9091 },
      quality: {
        loopPop: 0.91,
        heightSwing: 6.4,
        driftX: 6,
        warnings: [],
      },
    },
    doubtful: {
      file: 'fox-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0455, width: 1, height: 0.9091 },
      quality: {
        loopPop: 0.68,
        heightSwing: 8.5,
        driftX: 2,
        warnings: [],
      },
    },
    sneaky: {
      file: 'fox-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0455, width: 1, height: 0.9091 },
      quality: {
        loopPop: 0.9,
        heightSwing: 12.6,
        driftX: 11,
        warnings: [],
      },
    },
    talking: {
      file: 'fox-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0455, width: 1, height: 0.9091 },
      quality: {
        loopPop: 0.93,
        heightSwing: 10.8,
        driftX: 3.8,
        warnings: [],
      },
    },
    thinking: {
      file: 'fox-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0455, width: 1, height: 0.9091 },
      quality: {
        loopPop: 0.73,
        heightSwing: 16.4,
        driftX: 9.8,
        warnings: [],
      },
    },
  },
  mouse: {
    angry: {
      file: 'mouse-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0946, width: 1, height: 0.8108 },
      quality: {
        loopPop: 0.52,
        heightSwing: 1.7,
        driftX: 0,
        warnings: [],
      },
    },
    sneaky: {
      file: 'mouse-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0946, width: 1, height: 0.8108 },
      quality: {
        loopPop: 0.54,
        heightSwing: 3.9,
        driftX: 0.5,
        warnings: [],
      },
    },
    talking: {
      file: 'mouse-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0946, width: 1, height: 0.8108 },
      quality: {
        loopPop: 0.58,
        heightSwing: 1.1,
        driftX: 0,
        warnings: [],
      },
    },
    thinking: {
      file: 'mouse-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0946, width: 1, height: 0.8108 },
      quality: {
        loopPop: 0.62,
        heightSwing: 1.1,
        driftX: 0,
        warnings: [],
      },
    },
  },
  owl: {
    angry: {
      file: 'owl-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 0.27,
        heightSwing: 1.8,
        driftX: 0.5,
        warnings: [],
      },
    },
    approving: {
      file: 'owl-approving.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 1.31,
        heightSwing: 5.1,
        driftX: 2,
        warnings: [],
      },
    },
    doubtful: {
      file: 'owl-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 0.77,
        heightSwing: 8.6,
        driftX: 1,
        warnings: [],
      },
    },
    sneaky: {
      file: 'owl-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 0.38,
        heightSwing: 4.1,
        driftX: 4,
        warnings: [],
      },
    },
    talking: {
      file: 'owl-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 0.55,
        heightSwing: 5.2,
        driftX: 0.3,
        warnings: [],
      },
    },
    thinking: {
      file: 'owl-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1274, width: 1, height: 0.7452 },
      quality: {
        loopPop: 0.47,
        heightSwing: 2.9,
        driftX: 3,
        warnings: [],
      },
    },
  },
  pig: {
    angry: {
      file: 'pig-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1586, width: 1, height: 0.6828 },
      quality: {
        loopPop: 0.53,
        heightSwing: 6.7,
        driftX: 8,
        warnings: [],
      },
    },
    doubtful: {
      file: 'pig-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1586, width: 1, height: 0.6828 },
      quality: {
        loopPop: 0.74,
        heightSwing: 7.4,
        driftX: 4.5,
        warnings: [],
      },
    },
    talking: {
      file: 'pig-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1586, width: 1, height: 0.6828 },
      quality: {
        loopPop: 0.59,
        heightSwing: 11.3,
        driftX: 4,
        warnings: [],
      },
    },
    thinking: {
      file: 'pig-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1586, width: 1, height: 0.6828 },
      quality: {
        loopPop: 0.58,
        heightSwing: 8.3,
        driftX: 4.8,
        warnings: [],
      },
    },
  },
  raccoon: {
    angry: {
      file: 'raccoon-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1275, width: 1, height: 0.745 },
      quality: {
        loopPop: 0.59,
        heightSwing: 6.4,
        driftX: 7,
        warnings: [],
      },
    },
    doubtful: {
      file: 'raccoon-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1275, width: 1, height: 0.745 },
      quality: {
        loopPop: 0.66,
        heightSwing: 2.4,
        driftX: 3.5,
        warnings: [],
      },
    },
    sneaky: {
      file: 'raccoon-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1275, width: 1, height: 0.745 },
      quality: {
        loopPop: 0.62,
        heightSwing: 5.3,
        driftX: 5.5,
        warnings: [],
      },
    },
    talking: {
      file: 'raccoon-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1275, width: 1, height: 0.745 },
      quality: {
        loopPop: 0.55,
        heightSwing: 2.9,
        driftX: 3.8,
        warnings: [],
      },
    },
    thinking: {
      file: 'raccoon-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.1275, width: 1, height: 0.745 },
      quality: {
        loopPop: 0.62,
        heightSwing: 1.2,
        driftX: 0.8,
        warnings: [],
      },
    },
  },
  seagull: {
    angry: {
      file: 'seagull-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 36,
      frameRate: 12,
      cols: 6,
      fit: { x: 0, y: 0.074, width: 1, height: 0.8521 },
      quality: {
        loopPop: 0.25,
        heightSwing: 0.5,
        driftX: 3,
        warnings: [],
      },
    },
    doubtful: {
      file: 'seagull-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.074, width: 1, height: 0.8521 },
      quality: {
        loopPop: 2.99,
        heightSwing: 12.6,
        driftX: 11.5,
        warnings: ['loop seam 2.99% (over 2%) — it will visibly jump on every repeat'],
      },
    },
    sneaky: {
      file: 'seagull-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.074, width: 1, height: 0.8521 },
      quality: {
        loopPop: 0.45,
        heightSwing: 1,
        driftX: 4.3,
        warnings: [],
      },
    },
    talking: {
      file: 'seagull-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.074, width: 1, height: 0.8521 },
      quality: {
        loopPop: 1.17,
        heightSwing: 16.2,
        driftX: 8.3,
        warnings: [],
      },
    },
    thinking: {
      file: 'seagull-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 36,
      frameRate: 12,
      cols: 6,
      fit: { x: 0, y: 0.074, width: 1, height: 0.8521 },
      quality: {
        loopPop: 0.26,
        heightSwing: 0,
        driftX: 0.3,
        warnings: [],
      },
    },
  },
  skunk: {
    angry: {
      file: 'skunk-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0045, y: 0, width: 0.9911, height: 1 },
      quality: {
        loopPop: 1.15,
        heightSwing: 7.5,
        driftX: 2.8,
        warnings: [],
      },
    },
    doubtful: {
      file: 'skunk-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0045, y: 0, width: 0.9911, height: 1 },
      quality: {
        loopPop: 1.14,
        heightSwing: 3.4,
        driftX: 3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'skunk-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0045, y: 0, width: 0.9911, height: 1 },
      quality: {
        loopPop: 1.05,
        heightSwing: 8.5,
        driftX: 1,
        warnings: [],
      },
    },
    talking: {
      file: 'skunk-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0045, y: 0, width: 0.9911, height: 1 },
      quality: {
        loopPop: 0.99,
        heightSwing: 5.7,
        driftX: 4.5,
        warnings: [],
      },
    },
    thinking: {
      file: 'skunk-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0.0045, y: 0, width: 0.9911, height: 1 },
      quality: {
        loopPop: 1.21,
        heightSwing: 6.6,
        driftX: 0.8,
        warnings: [],
      },
    },
  },
  snake: {
    angry: {
      file: 'snake-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 36,
      frameRate: 12,
      cols: 6,
      fit: { x: 0, y: 0.0763, width: 1, height: 0.8475 },
      quality: {
        loopPop: 1.88,
        heightSwing: 3.4,
        driftX: 2.8,
        warnings: [],
      },
    },
    doubtful: {
      file: 'snake-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0763, width: 1, height: 0.8475 },
      quality: {
        loopPop: 0.32,
        heightSwing: 1.1,
        driftX: 0,
        warnings: [],
      },
    },
    sneaky: {
      file: 'snake-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0763, width: 1, height: 0.8475 },
      quality: {
        loopPop: 0.28,
        heightSwing: 5.3,
        driftX: 7,
        warnings: [],
      },
    },
    talking: {
      file: 'snake-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0763, width: 1, height: 0.8475 },
      quality: {
        loopPop: 1.64,
        heightSwing: 3.3,
        driftX: 3.3,
        warnings: [],
      },
    },
    thinking: {
      file: 'snake-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0763, width: 1, height: 0.8475 },
      quality: {
        loopPop: 0.24,
        heightSwing: 0,
        driftX: 0,
        warnings: [],
      },
    },
  },
  'white-chicken': {
    angry: {
      file: 'white-chicken-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0789, width: 1, height: 0.8421 },
      quality: {
        loopPop: 0.52,
        heightSwing: 3.7,
        driftX: 10,
        warnings: [],
      },
    },
    doubtful: {
      file: 'white-chicken-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 36,
      frameRate: 12,
      cols: 6,
      fit: { x: 0, y: 0.0789, width: 1, height: 0.8421 },
      quality: {
        loopPop: 0.32,
        heightSwing: 1,
        driftX: 14.3,
        warnings: [],
      },
    },
    sneaky: {
      file: 'white-chicken-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.0789, width: 1, height: 0.8421 },
      quality: {
        loopPop: 0.55,
        heightSwing: 0.5,
        driftX: 0.3,
        warnings: [],
      },
    },
    talking: {
      file: 'white-chicken-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 36,
      frameRate: 12,
      cols: 6,
      fit: { x: 0, y: 0.0789, width: 1, height: 0.8421 },
      quality: {
        loopPop: 0.42,
        heightSwing: 1,
        driftX: 11.3,
        warnings: [],
      },
    },
    thinking: {
      file: 'white-chicken-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 36,
      frameRate: 12,
      cols: 6,
      fit: { x: 0, y: 0.0789, width: 1, height: 0.8421 },
      quality: {
        loopPop: 0.52,
        heightSwing: 1,
        driftX: 1,
        warnings: [],
      },
    },
  },
  'white-sheep-1': {
    angry: {
      file: 'white-sheep-1-angry.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.015, width: 1, height: 0.9699 },
      quality: {
        loopPop: 1.46,
        heightSwing: 11.7,
        driftX: 13.8,
        warnings: [],
      },
    },
    doubtful: {
      file: 'white-sheep-1-doubtful.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.015, width: 1, height: 0.9699 },
      quality: {
        loopPop: 1.31,
        heightSwing: 10,
        driftX: 13,
        warnings: [],
      },
    },
    sneaky: {
      file: 'white-sheep-1-sneaky.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.015, width: 1, height: 0.9699 },
      quality: {
        loopPop: 1.23,
        heightSwing: 2.6,
        driftX: 1.5,
        warnings: [],
      },
    },
    talking: {
      file: 'white-sheep-1-talking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.015, width: 1, height: 0.9699 },
      quality: {
        loopPop: 0.76,
        heightSwing: 2.6,
        driftX: 6.3,
        warnings: [],
      },
    },
    thinking: {
      file: 'white-sheep-1-thinking.png',
      frameWidth: 256,
      frameHeight: 256,
      frameCount: 25,
      frameRate: 13,
      cols: 5,
      fit: { x: 0, y: 0.015, width: 1, height: 0.9699 },
      quality: {
        loopPop: 0.8,
        heightSwing: 5.2,
        driftX: 6.3,
        warnings: [],
      },
    },
  },
};
